### ISSUE TITLE
wi-fi

### ISSUE THREAD

**Issue by RicardoWosllan** [DaniloAgostinho/lab-alunos-comandos-linux#10]
danilo eu não consigo hackear meu vizinho o numero de sequencia de chaves no terminal não esta funcionando, oque eu faço?

**Comment by DaniloAgostinho** [comment]
@RicardoWosllan , Me desculpe mas acho que você não entendeu o objetivo do repositório. :-1: Não posso responder sua pergunta.

**Comment by Eidi199** [comment]
vai fazer alguma coisa na vida inves de hackiar vizinho kk

**Comment by gabrielsop15** [comment]
se loko nao manja nem hackear o vizinho
nub kkkkkk

**Comment by gabrielsop15** [comment]
a foto do thiago ... nao consigo saber se eh homen traveco ou mulher
to na duvida alguem ajuda kkkk

**Comment by DaniloAgostinho** [comment]
@Eidi199 , @gabrielsop12, 

 Lembrem-se, não devemos perder o espirito da ferramenta.

**Comment by RicardoWosllan** [comment]
Era só brincadeira Eidi 199, o Danilo me falou pra eu mandar uma mensagem e
eu mandei essa ai
Em 05/10/2015 17:05, "Eidi199" <notifications@github.com> escreveu:

**Comment by Eidi199** [comment]
seu nem tem foto então fica na tua filhão

**Comment by Eidi199** [comment]
HAUSHAUSHAUHUAHUAHUSAHU SALVE

**Comment by Eidi199** [comment]
bixo ta viciado msm hem

**Comment by gabrielsop15** [comment]
ue kkkk
sai desse bangue ricardo

**Comment by gabrielsop15** [comment]
e ricardo nao adianta procura ... aq nao tem porno parça

**Comment by RicardoWosllan** [comment]
Sai daqui vc
Em 05/10/2015 17:10, "gabrielsop15" <notifications@github.com> escreveu:

**Comment by Eidi199** [comment]
ooooooooooooooooooorra falo q a mae nasceu pelada em

**Comment by DaniloAgostinho** [comment]
@geral só excluindo a brincadeira maliciosa de vocês!

**Comment by RicardoWosllan** [comment]
Kkkk o azdeia
Em 05/10/2015 17:12, "Eidi199" <notifications@github.com> escreveu:

**Comment by DaniloAgostinho** [comment]
@RicardoWosllan quando você quiser mencionar alguém você precisa usar o @ para marcar a pessoa com quem tem objetivo de conversar. ;)
