### ISSUE TITLE
duvida sobre o cmando chmode

### ISSUE THREAD

**Issue by Marialie** [DaniloAgostinho/lab-alunos-comandos-linux#8]
p q serve  chmode

**Comment by DaniloAgostinho** [comment]
@Marialie ,

Primeiramente o comando se chama: chmod, se trata de um comando que adiciona/remove permissões em arquivos. Ex: adiciona/remover leitura, escrita e edição de um arquivos.

**Comment by DaniloAgostinho** [comment]
@Marialie :+1:  

bejo!

**Comment by Eidi199** [comment]
primeiramente, 
comando*
Chmod*

**Comment by Eidi199** [comment]
vamo pra aula de portugues 
bjo

**Comment by DaniloAgostinho** [comment]
@Eidi199 obrigado pela colaboração.
